# Generated by Django 6.0.7 on 2026-07-31 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('status', models.CharField(choices=[('게시', '게시'), ('초안', '초안'), ('숨김', '숨김')], default='게시', max_length=10)),
                ('sort', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('식이', '식이'), ('지압·마사지', '지압·마사지'), ('생활', '생활'), ('뜸', '뜸')], default='식이', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, max_length=255)),
                ('video', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'article',
                'ordering': ['sort'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('status', models.CharField(choices=[('게시', '게시'), ('초안', '초안'), ('숨김', '숨김')], default='게시', max_length=10)),
                ('sort', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('polarity', models.CharField(choices=[('권장', '권장'), ('제한', '제한')], default='권장', max_length=10)),
                ('component', models.CharField(blank=True, max_length=200)),
                ('foods', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'food',
                'ordering': ['sort'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HealthSign',
            fields=[
                ('status', models.CharField(choices=[('게시', '게시'), ('초안', '초안'), ('숨김', '숨김')], default='게시', max_length=10)),
                ('sort', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'health_sign',
                'ordering': ['sort'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Herb',
            fields=[
                ('status', models.CharField(choices=[('게시', '게시'), ('초안', '초안'), ('숨김', '숨김')], default='게시', max_length=10)),
                ('sort', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('hanja', models.CharField(blank=True, max_length=100)),
                ('image', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'herb',
                'ordering': ['sort'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('status', models.CharField(choices=[('게시', '게시'), ('초안', '초안'), ('숨김', '숨김')], default='게시', max_length=10)),
                ('sort', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'illness',
                'ordering': ['sort'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('status', models.CharField(choices=[('게시', '게시'), ('초안', '초안'), ('숨김', '숨김')], default='게시', max_length=10)),
                ('sort', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'nutrient',
                'ordering': ['sort'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('status', models.CharField(choices=[('게시', '게시'), ('초안', '초안'), ('숨김', '숨김')], default='게시', max_length=10)),
                ('sort', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('hanja', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('tip', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, max_length=255)),
                ('video', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'point',
                'ordering': ['sort'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('status', models.CharField(choices=[('게시', '게시'), ('초안', '초안'), ('숨김', '숨김')], default='게시', max_length=10)),
                ('sort', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, max_length=255)),
                ('url', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'product',
                'ordering': ['sort'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemType',
            fields=[
                ('status', models.CharField(choices=[('게시', '게시'), ('초안', '초안'), ('숨김', '숨김')], default='게시', max_length=10)),
                ('sort', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('body_value', models.IntegerField(default=50)),
                ('body_min', models.IntegerField(default=40)),
                ('body_max', models.IntegerField(default=60)),
                ('body_desc', models.TextField(blank=True)),
                ('herb_title', models.CharField(blank=True, max_length=200)),
                ('herb_desc', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'tem_type',
                'ordering': ['sort'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Weakness',
            fields=[
                ('status', models.CharField(choices=[('게시', '게시'), ('초안', '초안'), ('숨김', '숨김')], default='게시', max_length=10)),
                ('sort', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('wtype', models.CharField(choices=[('약점', '약점'), ('IDEA', 'IDEA')], default='약점', max_length=10)),
                ('catchphrase', models.CharField(blank=True, max_length=200)),
                ('speaker', models.CharField(blank=True, max_length=150)),
                ('source', models.CharField(blank=True, max_length=150)),
                ('aphorism', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'weakness',
                'ordering': ['sort'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.article')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.food')),
            ],
            options={
                'db_table': 'article_food',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='linked_foods',
            field=models.ManyToManyField(blank=True, related_name='articles', through='content.ArticleFood', to='content.food'),
        ),
        migrations.CreateModel(
            name='HerbCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanism', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sort', models.IntegerField(default=0)),
                ('herb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='content.herb')),
            ],
            options={
                'db_table': 'herb_card',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='NutrientCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perspective', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sort', models.IntegerField(default=0)),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='content.nutrient')),
            ],
            options={
                'db_table': 'nutrient_card',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='ArticlePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.article')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.point')),
            ],
            options={
                'db_table': 'article_point',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='linked_points',
            field=models.ManyToManyField(blank=True, related_name='articles', through='content.ArticlePoint', to='content.point'),
        ),
        migrations.CreateModel(
            name='ArticleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.article')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.product')),
            ],
            options={
                'db_table': 'article_product',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='linked_products',
            field=models.ManyToManyField(blank=True, related_name='articles', through='content.ArticleProduct', to='content.product'),
        ),
        migrations.CreateModel(
            name='TemTypeCuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('nutrient', '영양소'), ('herb', '약재'), ('food', '식품군')], max_length=10)),
                ('ref_id', models.CharField(max_length=20)),
                ('polarity', models.CharField(blank=True, max_length=10)),
                ('sort', models.IntegerField(default=0)),
                ('tem_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curations', to='content.temtype')),
            ],
            options={
                'db_table': 'tem_type_curation',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='TemTypeIllness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pct', models.IntegerField(default=0)),
                ('sort', models.IntegerField(default=0)),
                ('illness', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.illness')),
                ('tem_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='illness_links', to='content.temtype')),
            ],
            options={
                'db_table': 'tem_type_illness',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='TemTypeWeakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tem_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.temtype')),
                ('weakness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.weakness')),
            ],
            options={
                'db_table': 'tem_type_weakness',
            },
        ),
        migrations.AddField(
            model_name='temtype',
            name='weaknesses',
            field=models.ManyToManyField(blank=True, related_name='tem_types', through='content.TemTypeWeakness', to='content.weakness'),
        ),
        migrations.CreateModel(
            name='PointWeakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.point')),
                ('weakness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.weakness')),
            ],
            options={
                'db_table': 'point_weakness',
            },
        ),
        migrations.AddField(
            model_name='point',
            name='weaknesses',
            field=models.ManyToManyField(blank=True, related_name='points', through='content.PointWeakness', to='content.weakness'),
        ),
        migrations.CreateModel(
            name='NutrientCardWeakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.nutrientcard')),
                ('weakness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.weakness')),
            ],
            options={
                'db_table': 'nutrient_card_weakness',
            },
        ),
        migrations.AddField(
            model_name='nutrientcard',
            name='weaknesses',
            field=models.ManyToManyField(blank=True, related_name='nutrient_cards', through='content.NutrientCardWeakness', to='content.weakness'),
        ),
        migrations.CreateModel(
            name='IllnessWeakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.illness')),
                ('weakness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.weakness')),
            ],
            options={
                'db_table': 'illness_weakness',
            },
        ),
        migrations.AddField(
            model_name='illness',
            name='weaknesses',
            field=models.ManyToManyField(blank=True, related_name='illnesses', through='content.IllnessWeakness', to='content.weakness'),
        ),
        migrations.CreateModel(
            name='HerbCardWeakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.herbcard')),
                ('weakness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.weakness')),
            ],
            options={
                'db_table': 'herb_card_weakness',
            },
        ),
        migrations.AddField(
            model_name='herbcard',
            name='weaknesses',
            field=models.ManyToManyField(blank=True, related_name='herb_cards', through='content.HerbCardWeakness', to='content.weakness'),
        ),
        migrations.CreateModel(
            name='HealthSignWeakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.healthsign')),
                ('weakness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.weakness')),
            ],
            options={
                'db_table': 'health_sign_weakness',
            },
        ),
        migrations.AddField(
            model_name='healthsign',
            name='weaknesses',
            field=models.ManyToManyField(blank=True, related_name='health_signs', through='content.HealthSignWeakness', to='content.weakness'),
        ),
        migrations.CreateModel(
            name='FoodWeakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.food')),
                ('weakness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.weakness')),
            ],
            options={
                'db_table': 'food_weakness',
            },
        ),
        migrations.AddField(
            model_name='food',
            name='weaknesses',
            field=models.ManyToManyField(blank=True, related_name='foods', through='content.FoodWeakness', to='content.weakness'),
        ),
        migrations.CreateModel(
            name='ArticleWeakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.article')),
                ('weakness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.weakness')),
            ],
            options={
                'db_table': 'article_weakness',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='weaknesses',
            field=models.ManyToManyField(blank=True, related_name='articles', through='content.ArticleWeakness', to='content.weakness'),
        ),
        migrations.AddConstraint(
            model_name='articlefood',
            constraint=models.UniqueConstraint(fields=('article', 'food'), name='uniq_article_food'),
        ),
        migrations.AddConstraint(
            model_name='articlepoint',
            constraint=models.UniqueConstraint(fields=('article', 'point'), name='uniq_article_point'),
        ),
        migrations.AddConstraint(
            model_name='articleproduct',
            constraint=models.UniqueConstraint(fields=('article', 'product'), name='uniq_article_product'),
        ),
        migrations.AddConstraint(
            model_name='temtypeweakness',
            constraint=models.UniqueConstraint(fields=('tem_type', 'weakness'), name='uniq_tem_type_weakness'),
        ),
        migrations.AddConstraint(
            model_name='pointweakness',
            constraint=models.UniqueConstraint(fields=('point', 'weakness'), name='uniq_point_weakness'),
        ),
        migrations.AddConstraint(
            model_name='nutrientcardweakness',
            constraint=models.UniqueConstraint(fields=('card', 'weakness'), name='uniq_nutrient_card_weakness'),
        ),
        migrations.AddConstraint(
            model_name='illnessweakness',
            constraint=models.UniqueConstraint(fields=('illness', 'weakness'), name='uniq_illness_weakness'),
        ),
        migrations.AddConstraint(
            model_name='herbcardweakness',
            constraint=models.UniqueConstraint(fields=('card', 'weakness'), name='uniq_herb_card_weakness'),
        ),
        migrations.AddConstraint(
            model_name='healthsignweakness',
            constraint=models.UniqueConstraint(fields=('sign', 'weakness'), name='uniq_health_sign_weakness'),
        ),
        migrations.AddConstraint(
            model_name='foodweakness',
            constraint=models.UniqueConstraint(fields=('food', 'weakness'), name='uniq_food_weakness'),
        ),
        migrations.AddConstraint(
            model_name='articleweakness',
            constraint=models.UniqueConstraint(fields=('article', 'weakness'), name='uniq_article_weakness'),
        ),
    ]
