# Generated by Django 6.0.7 on 2026-07-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temtype',
            name='body_max',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='temtype',
            name='body_min',
            field=models.IntegerField(default=2),
        ),
    ]
