# Generated by Django 6.0.7 on 2026-08-03 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_temtype_body_max_alter_temtype_body_min'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeArticle',
            fields=[
                ('status', models.CharField(choices=[('게시', '게시'), ('초안', '초안'), ('숨김', '숨김')], default='게시', max_length=10)),
                ('sort', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('체온', '체온'), ('먹고싸고', '먹고싸고'), ('멘탈', '멘탈'), ('체질이야기', '체질이야기')], default='체온', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, max_length=255)),
                ('video', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'tem_daily',
                'ordering': ['sort'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LifeArticleLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('nutrient', '영양소'), ('herb', '약재'), ('food', '식품군'), ('point', '혈자리'), ('health_sign', '건강신호'), ('illness', '예측질환'), ('product', '제품'), ('article', '요법관리')], max_length=20)),
                ('ref_id', models.CharField(max_length=20)),
                ('sort', models.IntegerField(default=0)),
                ('life_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_links', to='content.lifearticle')),
            ],
            options={
                'db_table': 'tem_life_content_link',
                'ordering': ['sort'],
                'constraints': [models.UniqueConstraint(fields=('life_article', 'kind', 'ref_id'), name='uniq_life_article_link')],
            },
        ),
        migrations.CreateModel(
            name='LifeArticleRelated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(default=0)),
                ('from_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_links', to='content.lifearticle')),
                ('to_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='content.lifearticle')),
            ],
            options={
                'db_table': 'tem_related',
                'ordering': ['sort'],
                'constraints': [models.UniqueConstraint(fields=('from_article', 'to_article'), name='uniq_life_article_related')],
            },
        ),
    ]
