# Generated by Django 6.0.7 on 2026-07-31 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7)),
                ('reviewer', models.CharField(max_length=100)),
                ('finding', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.CharField(max_length=64)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('target_user', models.CharField(blank=True, max_length=64, null=True)),
                ('fields', models.CharField(blank=True, max_length=255)),
                ('purpose', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['target_user', '-created_at'], name='audit_acces_target__24b41a_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.CharField(blank=True, max_length=64, null=True)),
                ('actor_type', models.CharField(default='admin', max_length=20)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('action', models.CharField(choices=[('create', 'create'), ('update', 'update'), ('delete', 'delete'), ('publish', 'publish'), ('export', 'export')], max_length=10)),
                ('target_table', models.CharField(max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=64, null=True)),
                ('before_json', models.TextField(blank=True, null=True)),
                ('after_json', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['target_table', 'target_id', '-created_at'], name='audit_audit_target__0e377a_idx'), models.Index(fields=['actor_id', '-created_at'], name='audit_audit_actor_i_1175ab_idx')],
            },
        ),
    ]
