# Generated by Django 6.0.7 on 2026-08-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'create'), ('update', 'update'), ('delete', 'delete'), ('publish', 'publish'), ('export', 'export'), ('deny', 'deny')], max_length=10),
        ),
    ]
