# Generated by Django 6.0.7 on 2026-08-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'create'), ('update', 'update'), ('delete', 'delete'), ('publish', 'publish'), ('export', 'export'), ('deny', 'deny'), ('read', 'read')], max_length=10),
        ),
    ]
