# Generated by Django 6.0.7 on 2026-08-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('director', models.CharField(blank=True, max_length=50)),
                ('sido', models.CharField(blank=True, max_length=20)),
                ('sigungu', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('hours', models.TextField(blank=True)),
                ('intro', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, max_length=255)),
                ('map_url', models.CharField(blank=True, max_length=500)),
                ('homepage', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('게시', '게시'), ('숨김', '숨김')], default='게시', max_length=10)),
                ('sort', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'clinic',
                'ordering': ['sort', 'id'],
            },
        ),
    ]
