# Generated by Django 6.0.7 on 2026-07-31 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.CharField(max_length=20)),
                ('day', models.DateField()),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('type_id', 'day'), name='uniq_diagnosis_stat')],
            },
        ),
        migrations.CreateModel(
            name='DiagnosisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.CharField(blank=True, max_length=20, null=True)),
                ('raw_value', models.IntegerField(blank=True, null=True)),
                ('provider', models.CharField(default='mock', max_length=20)),
                ('status', models.CharField(choices=[('대기', '대기'), ('완료', '완료'), ('실패', '실패'), ('타임아웃', '타임아웃')], default='완료', max_length=10)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='diagnosis_d_user_id_541e68_idx')],
            },
        ),
    ]
