# Generated by Django 6.0.7 on 2026-08-02 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsDocument',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sort', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConsentItem',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('required', models.BooleanField(default=True)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('channel', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('sort', models.IntegerField(default=0)),
                ('status', models.CharField(default='게시', max_length=10)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_items', to='consent.termsdocument')),
            ],
            options={
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TermsVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('effective_at', models.DateField()),
                ('is_major', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('초안', '초안'), ('예약', '예약'), ('게시', '게시'), ('폐기', '폐기')], default='초안', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='consent.termsdocument')),
            ],
            options={
                'ordering': ['document', '-effective_at'],
            },
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed', models.BooleanField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_consents', to='consent.consentitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_consents', to='consent.termsversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='termsversion',
            constraint=models.UniqueConstraint(fields=('document', 'version'), name='uniq_terms_version'),
        ),
        migrations.AddIndex(
            model_name='userconsent',
            index=models.Index(fields=['user', 'item', '-created_at'], name='consent_use_user_id_6fefe6_idx'),
        ),
    ]
